steps:
  - label: ":macos: b12y-MBP"
    commands:
    - "darwin-rebuild build --flake .#b12y-MBP"
    - "darwin-rebuild check --flake .#b12y-MBP"

  - label: ":macos: JamesBookPro16"
    commands:
    - "darwin-rebuild build --flake .#JamesBookPro16"
    - "darwin-rebuild check --flake .#JamesBookPro16"
